### PR TITLE
Fixes for issue #7, #8, #10 and  #11

### PR DESCRIPTION
**Pull request by unicod3**
Hi, 
First of all thanks for this great repo. 
I tried to initialize the formset in a modal but I had this problem that when I first open model and click the add button everything works fine but then if I don't refresh the page and open another modal with formset and click the add button it added more than one form(in the numbers of models that i open and close). 
That was a strange issue and I found that if I add off method before the on method issue fixed.  #11

### CODE REVIEW

**Comment by unicod3** [comment]
Later on, I also had to add the fix  @truhlik suggested on #7 for my project

**Comment by unicod3** [comment]
Well, this will also fix #10 with the commit 3 but I think #10 can be solved with a better approach.

**Comment by unicod3** [comment]
Well, I also write a method for issue #8 
Now it hides the last item's delete button, and if you click the add button it shows the delete button again.

**Comment by truhlik** [comment]
Hi @unicod3 thank you for these commits. 

I have tested and found one bug. I found that DELETE button is completely missing in all forms in formset. But after clicking on ADD button then  DELETE button appears everywhere.
I check your code, but don't see any problem. Could you fix? Thank you.

**Pull request closed without merging**
